### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by bartTC** [bartTC/pip-check#1]
My initial idea was to have a `pip` GUI. I started diving into `curses` but obviously `curses` was invented to make people cry, so I deferred that in favor of a simple table for now.

The rough plan:
- Have an interactive mode, every package selectable, using up/down arrows
- Hit enter to update to the latest version
- Other key to go to the pypi page
- Have an optional `-r requirements.txt` argument, and if thats present:
  - only display packages which are also present in the requirements file
  - if I update using enter key, it also saves the new version in the requirements file. Similar to `--save` in npm.
- ...

**Comment by cleder** [comment]
I wonder if 
https://pypi.python.org/pypi/pytablewriter/
could come in useful to format the output?

**Comment by bartTC** [comment]
I have not had the need to update pypi packages using a cli tool directly, the other features are implemented in version 2.0.
