### ISSUE TITLE
'pip-check' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by JattMones** [bartTC/pip-check#19]
I've downloaded the latest version of python and pip as of today (8/5/2019), and after successfully installing pip-check I receive this error when running 'pip check' in my terminal. If I'm missing a step, could you please further update the readme to avoid this problem?

![Command Prompt 8_5_2019 10_02_35 AM](https://user-images.githubusercontent.com/22432176/62470341-3b3f5980-b768-11e9-8af6-7cf095e42843.png)

**Comment by bartTC** [comment]
Mmh generally that looks all right to me but:

- I've never tested it under Windows and am totally unfamiliar with it. It might need additional work to have it a working script there. 
- Do you maybe need to add the directory of these binaries to your $PATH? 
- Do `pip install django`. Django does also install a script. Does `django-admin` or `django-admin.py` work for you?

**Comment by JattMones** [comment]
Hi again, I installed django with pip and ran django-admin successfully. While it could be the $PATH, I think that it may be more complicated then that due to the message in the screenshot below. It seems that while pip-check is recognized as installed by pip, it isn't recognized by Python. After doing some more digging, I noticed the "pip-check file" in the python/Scripts folder was not a .py file, so I fixed that but it didn't change anything.

Please let me know if there's anything else you recommend trying.

![Command Prompt 8_6_2019 1_27_56 PM](https://user-images.githubusercontent.com/22432176/62561861-0ad1eb00-b84e-11e9-8f82-02e0768340ff.png)

**Comment by JattMones** [comment]
I got it to run in it's current directory, which can add a pip-check shorthand command for manually. However, after running some tests it seems like there's something wrong with the colors on Windows. I researched the colorclass package, and found that I needed to add the 'colorclass.Windows.enable(auto_colors=True, reset_atexit=True)' to the python file for it to work. As you can see, colored text can be displayed this way, but whenever it is loaded into the dictionary to then be loaded into the table data, the color isn't preserved. There is an odd code instead (the data is additionally printed above each table). While testing it, it seems like it is due to the color being loaded into the dictionary. I'll try and see if I can bypass using a dictionary for this, but that seems like a pretty big code change. Perhaps using a different color or table module on Windows would be a better solution. 
![Command Prompt - cmd 8_6_2019 4_09_37 PM](https://user-images.githubusercontent.com/22432176/62574296-29dc7700-b866-11e9-9afd-9c49ab3d964c.png)

**Comment by JattMones** [comment]
For now, my temporary solution is to just remove colors all together on Windows. The table format is what I was really after. Perhaps update the readME to say further testing and development is needed on windows, and reference this issue.

**Comment by bartTC** [comment]
Version 2.5.1 should fix your PATH issues. It's now setup the same way as Django or pip. It works in my Windows 7 Testbox.

Do `pip uninstall pip-check` and then `pip install pip-check==2.5.1`. 

![](https://d.pr/i/HWya57.png)

As you can see in the screenshot I couldn't figure out the color issue either. I added the Windows.enable function but it didn't have effect. I need to dive deeper into it, and probably test it with a more recent Windows version.

You can disable it with `--disable-colors` in the meantime.
