### ISSUE TITLE
Incompatibility with older pip

### ISSUE THREAD

**Issue by jayvdb** [bartTC/pip-check#27]
```py
[   53s] + python3 /home/abuild/rpmbuild/BUILDROOT/python-pip-check-2.6-2.1.x86_64/usr/bin/pip-check
[   53s] Traceback (most recent call last):
[   53s]   File "/home/abuild/rpmbuild/BUILDROOT/python-pip-check-2.6-2.1.x86_64/usr/bin/pip-check", line 11, in <module>
[   53s]     load_entry_point('pip-check==2.6', 'console_scripts', 'pip-check')()
[   53s]   File "/home/abuild/rpmbuild/BUILDROOT/python-pip-check-2.6-2.1.x86_64/usr/lib/python3.4/site-packages/pip_check/__init__.py", line 293, in main
[   53s]     check_pip_version(options)
[   53s]   File "/home/abuild/rpmbuild/BUILDROOT/python-pip-check-2.6-2.1.x86_64/usr/lib/python3.4/site-packages/pip_check/__init__.py", line 115, in check_pip_version
[   53s]     cmd_response = subprocess.run(
[   53s] AttributeError: 'module' object has no attribute 'run'
```

I have checked and `callable-pip` works, but I suspect it isnt always reporting exit status correctly.
https://build.opensuse.org/package/show/home:jayvdb:py-new/python-callable-pip

Or use pip-api or pip-shims

**Comment by bartTC** [comment]
You run into this

https://docs.python.org/3/library/subprocess.html

> The run() function was added in Python 3.5; if you need to retain compatibility with older versions, see the Older high-level API section.

Python 3.4 is not supported, you shouldn't be able to install it. https://github.com/bartTC/pip-check/blob/master/setup.py#L29 I can see you have it in `/usr/bin/pip-check` so you must go through the setup.py install right? 

The lifecylcle of 3.4 has ended last March. https://devguide.python.org/devcycle/#end-of-life-branches

**Comment by jayvdb** [comment]
Ah ok. I'll disable 3.4 builds.
