### ISSUE TITLE
AttributeError: 'ListCommand' object has no attribute 'find_packages_latest_versions'

### ISSUE THREAD

**Issue by Loc-Tran** [bartTC/pip-check#3]
user@user-desktop:~/Desktop$ pip-check
Traceback (most recent call last):
  File "/home/user/.local/bin/pip-check", line 19, in <module>
    package_list = ListCommand().find_packages_latest_versions(options)
AttributeError: 'ListCommand' object has no attribute 'find_packages_latest_versions'

Not sure what's going on but it doesn't seem to work. Installed via pip.

**Comment by bartTC** [comment]
See issue #2. It's fixed here on Github already but not released on Pypi yet.

**Comment by jason-kane** [comment]
I get exactly the same error from a fresh clone.

$ pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

if I upgrade pip to 8.0.2 (pip install --upgrade pip) then pip-check works as expected.

**Comment by jason-kane** [comment]
to be fair, the README does say: "Requires pip Version 6 or higher."  It may be worth checking the pip version and exiting with a friendly you-need-to-upgrade-your-pip message.

**Comment by bartTC** [comment]
That is a good idea. #6
