### ISSUE TITLE
Odd Table Formatting

### ISSUE THREAD

**Issue by anthonydb** [bartTC/pip-check#33]
Recently started getting this table formatting with pip-check:

![Screen Shot 2022-09-19 at 3 50 28 PM](https://user-images.githubusercontent.com/273891/191104076-77444b20-5dfb-4c4b-bc88-206e2e58998a.png)

I'm on Python 3.9.7 on macOS Monterey.

**Comment by bartTC** [comment]
I guess you updated your terminal or changed settings there. It's not related to python but the encoding of the terminal. I assume, tools like `htop` also break right?

You can bypass this with `pip-check -a` to use ascii tables.
