### ISSUE TITLE
Confusion: pip-check thinks 1.0.0 < 0.9.9

### ISSUE THREAD

**Issue by samueljohn** [bartTC/pip-check#9]
I like `pip-check` a lot. Thanks.

I have locally a dev version `1.0.0` of pydicom and PyPI has `0.9.9`, so I guess it should not show this package in "Minor Release Update". See below.

Further `vispy` is 0.5.0.dev0 where PyPI has got 0.4.0. But this one obviously is a harder nut because of parsing the "dev0" thing...

I am using python 3.5 and `pip-check-0.2`.

```
┌──────────────────────┬────────────┬────────┬──────────────────────────────────────────────┐
│ Minor Release Update │ Version    │ Latest │                                              │
├──────────────────────┼────────────┼────────┼──────────────────────────────────────────────┤
│ pydicom              │ 1.0.0      │ 0.9.9  │ https://pypi.python.org/pypi/pydicom         │
│ vispy                │ 0.5.0.dev0 │ 0.4.0  │ https://pypi.python.org/pypi/vispy           │
```

**Comment by bartTC** [comment]
I wasn't able to test this with this specific package but I believe its fixed in the latest version 2.0.

I put those type of packages now into the 'unknown' section. I think thats more appropriate than 'unchanged'.
